# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        cache: ~

        # the name of the "filter set"
        offer_thumb_default:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [ 244, 114 ], mode: outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
#                background: { size: [ 124, 94 ], position: center, color: '#000000' }
        offer_thumb_sm:
            quality: 75
            filters:
                thumbnail: { size: [ 532.4, 200 ], mode: outbound, allow_upscale: true }
        offer_thumb_lg:
            quality: 75
            filters:
                thumbnail: { size: [ 334, 150 ], mode: outbound, allow_upscale: true }
        offer_thumb_xl:
            quality: 75
            filters:
                thumbnail: { size: [ 189.16, 326 ], mode: outbound, allow_upscale: true }
        offer_thumb_xml:
            quality: 75
            filters:
                thumbnail: { size: [ 226, 302 ], mode: outbound, allow_upscale: true }
        offer_thumb_xxl:
            quality: 75
            filters:
                thumbnail: { size: [ 264.16, 302 ], mode: outbound, allow_upscale: true }
        home_thumb_first_image:
            quality: 75
            filters:
                thumbnail: { size: [ 1638, 500 ], mode: outbound, allow_upscale: true }