vich_uploader:
    db_driver: orm

    mappings:
        provider_files:
    #        uri_prefix: /images/products
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
